language: php
sudo: true

cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"

php:
  - 7.1

git:
  depth: 5

env:
  global:
    # Set site environment
    - AH_SITE_ENVIRONMENT=travis

# Use newer distribution on Travis CI (Ubuntu 14.04 - Trusty)
dist: trusty

# travis will test and deploy only the branches and tags as show below
# right now travis does not make a difference between branches and tags
# tags starting with hotfix and tags in the form of "v1.0.0" will be tested
branches:
  only:
    - master
    - develop
    - testing
    - /^8\.x-[0-9]+\.x/
    - /^hotfix/
    - /^v[0-9]+\.[0-9]+\.[0-9]+/

mysql:
  database: drupal
  username: root
  encoding: utf8

install:
  # Disable debugging
  - phpenv config-rm xdebug.ini

  # Setup display for Selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

  # Increase the MySQL connection timeout on the PHP end.
  - "mysql -e 'create database drupal;'"

  # Build drush/phing dependencies
  - travis_retry composer self-update && composer --version
  - travis_retry composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader
  - export PATH="$TRAVIS_BUILD_DIR/bin:$PATH"

  # Setting Behat environment
  - BUILD_TOP=`dirname $TRAVIS_BUILD_DIR`
  - BEHAT_PARAMS='{"extensions":{"Drupal\\DrupalExtension":{"drupal":{"drupal_root":"BUILD_TOP/docroot"}}}}'
  - BEHAT_PARAMS=`echo $BEHAT_PARAMS | sed -e s#BUILD_TOP#$TRAVIS_BUILD_DIR#`
  - export BEHAT_PARAMS

  # Get Selenium
  - wget http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.0.jar
  - java -jar selenium-server-standalone-2.53.0.jar > /dev/null 2>&1 &

  # Setup files
  - chmod -R 777 docroot/sites/default
  - cp ci/travis/travis.settings.php docroot/sites/default/settings.travis.php

  # Disable sendmail
  - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # set php timeouts
  - echo "mysql.connect_timeout=3000" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "default_socket_timeout=3000" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Increase the MySQL server timetout and packet size.
  - mysql -e "SET GLOBAL wait_timeout = 36000;"
  - mysql -e "SET GLOBAL max_allowed_packet = 33554432;"

before_script:
  # Install site
  - $TRAVIS_BUILD_DIR/bin/robo site:install $AH_SITE_ENVIRONMENT

  # Start web server
  - cd $TRAVIS_BUILD_DIR/docroot
  - drush runserver 8888 > /dev/null 2>&1 &

  - drush pm-uninstall dblog --yes
  - drush cset system.site page.front /taxonomy/term/1 --yes

  # Test if server started
  - nc -zvv localhost 4444; out=$?; while [[ $out -ne 0 ]]; do echo "Retry hit port 4444..."; nc -zvv localhost 4444; out=$?; sleep 1; done
  - nc -zvv localhost 8888; out=$?; while [[ $out -ne 0 ]]; do echo "Retry hit port 8888..."; nc -zvv localhost 8888; out=$?; sleep 1; done

script:
  # Check composer update (works only for cron executions)
  - bash -e $TRAVIS_BUILD_DIR/ci/travis/scripts/test-composer-update.sh

  # Run Behat tests.
  - $TRAVIS_BUILD_DIR/bin/behat --config $TRAVIS_BUILD_DIR/tests/behat/travis.behat.yml

after_success:
  - $TRAVIS_BUILD_DIR/ci/travis/scripts/deploy.sh

notifications:
  slack: burda-thunder:tZERC5knpxVIePPgokBdPZhI
